<a href="https://colab.research.google.com/github/PriyanshuRanjann/PriyanshuRanjann/blob/main/pandas%20tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


In [2]:
a=np.array([[2,3,4,5,6],[4,7,2,66,4],[54,76,3,23,78]])

In [3]:
a

array([[ 2,  3,  4,  5,  6],
       [ 4,  7,  2, 66,  4],
       [54, 76,  3, 23, 78]])

In [4]:
b=np.array([[21,3,84,15,6],[48,7,12,69,4],[54,76,3,23,78]])

In [5]:
b

array([[21,  3, 84, 15,  6],
       [48,  7, 12, 69,  4],
       [54, 76,  3, 23, 78]])

In [6]:
c=a.dot(b.transpose())

In [7]:
c

array([[  498,   534,   931],
       [ 1287,  4835,  2584],
       [ 2427,  5059, 15314]])

In [8]:
b.transpose()

array([[21, 48, 54],
       [ 3,  7, 76],
       [84, 12,  3],
       [15, 69, 23],
       [ 6,  4, 78]])

In [9]:
a.argmax()

14

In [10]:
a.argmin()

0

In [11]:
df=pd.DataFrame()

In [12]:
df


Empty DataFrame
Columns: []
Index: []

In [13]:
print(df)

Empty DataFrame
Columns: []
Index: []


In [14]:
df1=pd.DataFrame([[23,45,65,76,242,1,3],[23,5,6,7,8,9,1],[56,13,12,23,34,56,78],[67,21,12,12,34,45,67],[2,45,78,8,56,3,24]], columns=['A','B','C','D','E','F','G'])

In [15]:
df1

A   B   C   D    E   F   G
0  23  45  65  76  242   1   3
1  23   5   6   7    8   9   1
2  56  13  12  23   34  56  78
3  67  21  12  12   34  45  67
4   2  45  78   8   56   3  24

In [16]:
df1.head(2)

A   B   C   D    E  F  G
0  23  45  65  76  242  1  3
1  23   5   6   7    8  9  1

In [17]:
df1.tail(2)

A   B   C   D   E   F   G
3  67  21  12  12  34  45  67
4   2  45  78   8  56   3  24

In [18]:
df1.shape


(5, 7)

In [19]:
df1.iloc[0:3,0:3]

A   B   C
0  23  45  65
1  23   5   6
2  56  13  12

In [20]:
df1.dtypes

A    int64
B    int64
C    int64
D    int64
E    int64
F    int64
G    int64
dtype: object