<a href="https://colab.research.google.com/github/PriyanshuRanjann/PriyanshuRanjann/blob/main/Starting%20with%20numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
list1=[1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


In [37]:
import numpy as np

In [38]:
arr=np.arange(1000000)


In [39]:
pythlist=list(range(1000000
                    ))

In [40]:
%time for _ in range(10):arr=arr*3

CPU times: user 12.5 ms, sys: 5.15 ms, total: 17.6 ms
Wall time: 18.5 ms


In [41]:
np.array([1,2,3,5,7,9,0])


array([1, 2, 3, 5, 7, 9, 0])

In [42]:
array1=np.array([[2,5,8,2,3],[5,7,8,1,5]],dtype='int64')

In [43]:
print(array1)

[[2 5 8 2 3]
 [5 7 8 1 5]]


In [44]:
array1.shape

(2, 5)

In [45]:
array1.dtype

dtype('int64')

In [46]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [47]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [48]:
np.empty((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [49]:
array2=np.array([2,4,5,6,7,9,10])

In [50]:
arr=array2[4:6]

In [51]:
arr

array([7, 9])

In [52]:
arr[0]=9

In [53]:
array2

array([ 2,  4,  5,  6,  9,  9, 10])

In [54]:

ar1=np.array ([[1,2,3,4],
              [5,6,7,8]])

In [55]:
ar1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
ar1.sum(axis=1)

array([10, 26])

In [57]:
ar1.sum(axis=0)

array([ 6,  8, 10, 12])

In [58]:
b=np.array([[8,9,10,12],
            [5,2,9,0]])

In [59]:
ar1.dot(b.transpose())

array([[104,  36],
       [260, 100]])

In [60]:
len(dir(np))

609

In [63]:
np.cross(ar1,b)

ValueError: ignored

In [68]:
a=np.array([[5,29,1],
            [98,33,14]])

In [65]:
np.sort(a)

array([[ 1,  5, 29],
       [14, 33, 98]])

In [67]:
np.sort(a,axis=0,kind='mergesort')

array([[ 5, 29,  1],
       [98, 33, 14]])

In [71]:
x=np.arange(6)

In [72]:
x

array([0, 1, 2, 3, 4, 5])

In [87]:
y=np.array([12,3,4,13,53,57,24,24,31,42,45,65,78,4,34,13,67,23])

In [88]:
y.shape

(18,)

In [89]:
y

array([12,  3,  4, 13, 53, 57, 24, 24, 31, 42, 45, 65, 78,  4, 34, 13, 67,
       23])

In [90]:
np.argsort(y)



array([ 1,  2, 13,  0,  3, 15, 17,  7,  6,  8, 14,  9, 10,  4,  5, 11, 16,
       12])

In [91]:
np.argmin(y)

1

In [92]:
np.argmax(y)

12